#!/bin/bash
#docker run -it -p 127.0.0.1:6990:6990 -v /home/signed/.m2/repository:/repository bamboo /bin/bash
docker run -it --publish 127.0.0.1:6990:6990 --volume $HOME/.m2/repository:/repository bamboo $@